name: Auto Git Push Action

on:
  push:
    branches:
      -master
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 17:00
    - cron: '0 5 * * *'   # Runs every day at 05:00

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: create msg.txt
        run: echo "This is a msg"  > msg.txt

      - name: Print working dir
        run: pwd


      - name: Print msg
        run: cat msg.txt

      - name: echo msg
        run: echo "this is a custom msg"
    
